-- Evoluciona el chat existente sin crear un helpdesk paralelo ni adjuntos.
-- La aplicación mantiene acceso exclusivamente server-side mediante service role.

alter table public.support_conversations
  add column if not exists reference_number bigint generated by default as identity (start with 1000),
  add column if not exists customer_last_seen_at timestamptz,
  add column if not exists handled_by_admin_id uuid
    references public.admin_accounts(id) on delete set null,
  add column if not exists handled_by_admin_name text,
  add column if not exists handled_by_admin_email text,
  add column if not exists last_replied_by_admin_id uuid
    references public.admin_accounts(id) on delete set null,
  add column if not exists evidence_requested_at timestamptz,
  add column if not exists evidence_requested_by uuid
    references public.admin_accounts(id) on delete set null,
  add column if not exists evidence_received_at timestamptz,
  add column if not exists evidence_received_by uuid
    references public.admin_accounts(id) on delete set null,
  add column if not exists resolved_at timestamptz,
  add column if not exists resolved_by_admin_id uuid
    references public.admin_accounts(id) on delete set null,
  add column if not exists resolved_by_admin_name text,
  add column if not exists related_order_id text,
  add column if not exists related_order_name text,
  add column if not exists issue_category text,
  add column if not exists issue_subcategory text,
  add column if not exists diagnosed_at timestamptz;

alter table public.support_conversations
  drop constraint if exists support_conversations_issue_category_check,
  add constraint support_conversations_issue_category_check
    check (issue_category is null or issue_category in (
      'order', 'payment', 'points', 'account', 'product', 'other'
    ));

create unique index if not exists support_conversations_reference_number_idx
  on public.support_conversations (reference_number);

alter table public.support_conversations
  drop constraint if exists support_conversations_status_check;

update public.support_conversations
set status = case status
  when 'closed' then 'resolved'
  when 'open' then 'in_progress'
  when 'answered' then 'in_progress'
  else status
end;

alter table public.support_conversations
  add constraint support_conversations_status_check
  check (status in ('new', 'in_progress', 'waiting_information', 'resolved'));

alter table public.support_messages
  add column if not exists sender_id text,
  add column if not exists sender_name text,
  add column if not exists emailed_at timestamptz,
  add column if not exists email_provider_id text,
  add column if not exists request_id uuid;

alter table public.support_messages
  drop constraint if exists support_messages_sender_check,
  drop constraint if exists support_messages_delivery_channel_check,
  drop constraint if exists support_messages_email_status_check;

update public.support_messages
set delivery_channel = 'chat_and_email'
where delivery_channel = 'chat_email';

update public.support_messages
set email_status = 'not_required'
where email_status = 'not_requested';

update public.support_messages message
set
  sender_id = coalesce(
    message.sender_id,
    case
      when message.sender = 'admin' then message.admin_account_id::text
      else conversation.customer_id::text
    end
  ),
  sender_name = coalesce(
    nullif(trim(message.sender_name), ''),
    case
      when message.sender = 'admin' then (
        select account.full_name
        from public.admin_accounts account
        where account.id = message.admin_account_id
      )
      else coalesce(conversation.customer_name, 'Cliente')
    end
  )
from public.support_conversations conversation
where conversation.id = message.conversation_id;

alter table public.support_messages
  alter column sender_name set default 'Sistema',
  alter column sender_name set not null,
  alter column email_status set default 'not_required',
  add constraint support_messages_sender_check
    check (sender in ('customer', 'admin', 'system')),
  add constraint support_messages_delivery_channel_check
    check (delivery_channel in ('chat', 'chat_and_email')),
  add constraint support_messages_email_status_check
    check (email_status in ('not_required', 'pending', 'sent', 'failed'));

create unique index if not exists support_messages_request_id_idx
  on public.support_messages (request_id)
  where request_id is not null;

create index if not exists support_conversations_handler_idx
  on public.support_conversations (handled_by_admin_id, last_message_at desc)
  where handled_by_admin_id is not null;

create index if not exists support_conversations_last_replied_admin_idx
  on public.support_conversations (last_replied_by_admin_id)
  where last_replied_by_admin_id is not null;

create index if not exists support_conversations_evidence_requested_by_idx
  on public.support_conversations (evidence_requested_by)
  where evidence_requested_by is not null;

create index if not exists support_conversations_evidence_received_by_idx
  on public.support_conversations (evidence_received_by)
  where evidence_received_by is not null;

create index if not exists support_conversations_resolved_by_admin_idx
  on public.support_conversations (resolved_by_admin_id)
  where resolved_by_admin_id is not null;

create index if not exists support_conversations_presence_idx
  on public.support_conversations (customer_last_seen_at desc)
  where customer_last_seen_at is not null;

create index if not exists support_conversations_category_status_idx
  on public.support_conversations (issue_category, status, last_message_at desc)
  where issue_category is not null;

comment on column public.support_conversations.customer_last_seen_at is
  'Heartbeat aproximado de la clienta. En línea se calcula en servidor; no es un booleano persistente.';

comment on column public.support_messages.request_id is
  'Clave de idempotencia del envío del mensaje; nunca representa identidad o autorización.';
